server:
  port: 7010

spring:
  datasource:
    url: jdbc:mysql://192.168.1.148:3306/stremio_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

addon:
  name: "Addon Torrent"
  searchers:
    file:
      path: ${CONFIG_PATH:/tmp}
  jackett:
    apiKey: "cdbz8t1yuz5oz5fsr9z74kj4gay86b2r"
  tmbd:
    apiUrl: "https://api.themoviedb.org/3"
    apiKey: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkMjIyMWRiODNjM2MxYWIxMTM4M2Y5MDY2MTkzODAwOSIsIm5iZiI6MTcyODg4Nzc3OC41NzYxNzYsInN1YiI6IjY2NzU0OWVjMWE3YzZiYjQ3NTE2ZmM3MiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.fSJq0Dio4tLcL2lhe7XYBMoGNltnKp_K_to3buLzg7s"
    accountId: 21340220
trakt:
  client-id: 837b293ac8605e224146e7c78485166ca12bbe8d63643e24e9e60c33de9c713a
  client-secret: 3441fa665cd1a87204d31c512d756cdf84b3589cedb985cc5af789c240a13c96
  redirect-uri: http://localhost:7010/oauth/callback

logging:
  level:
    root: INFO